import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledRegistry from "./lib/StyledRegistry";
import { Nav } from "./components/Nav";
import { ConfigProvider } from "antd";
import { Top } from "./components/Top";
import Footer from "./components/home/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: "#0000e6",
            fontFamily: inter.className,
            colorTextSecondary: "#ffffff",
          },
          components: {
            Collapse: {
              headerBg: "#1E40AF",
              colorTextHeading: "#ffffff",
            },
            Breadcrumb: {
              itemColor: "#FFFFFF",
              linkColor: "#FFFFFF",
              linkHoverColor: "#FFFFFF",
              colorBgTextHover: "#0000e6",
              lastItemColor: "#FACC15",
              separatorColor: "#FFFFFF",
            },
            Menu: {
              darkItemBg: "#0000e6",
              darkItemHoverColor: "#FFFFFF",
              darkItemSelectedColor: `#ffff00 !important`,
              darkItemSelectedBg: "#d3d5db",
              // darkSubMenuItemBg: "#FFFFFF",
            },
            // Dropdown: {
            //   colorBgContainer: "#FFFFFF",
            //   colorBorder: "#FFFFFF",
            // },
            Card: {
              colorBgContainer: "#d3d5db",
            },
            Form: {
              colorText: "#FFFFFF",
              labelColor: "#FFFFFF",
            },
          },
        }}
      >
        <body className={inter.className}>
          <StyledRegistry>
            <main>
              <Top />
              <Nav />
              {children}
            </main>

            <Footer />
          </StyledRegistry>
        </body>
      </ConfigProvider>
    </html>
  );
}
