import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledRegistry from "./lib/StyledRegistry";
import { Nav } from "./components/Nav";
import { ConfigProvider, Affix } from "antd";
import { Top } from "./components/Top";
import Footer from "./components/home/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: "#0000e6",
            fontFamily: inter.className,
            colorTextSecondary: "#ffffff",
          },
          components: {
            Collapse: {
              // headerBg: "#0000e6",
            },
            Breadcrumb: {
              itemColor: "#231F20",
              linkColor: "#231F20",
              linkHoverColor: "#FFFFFF",
              colorBgTextHover: "#BA0C2F",
              lastItemColor: "#BA0C2F",
            },
            Menu: {
              // fontSize: 15,
              darkItemBg: "#0000e6",
              // darkDangerItemActiveBg: "#ffff00",
              darkItemSelectedColor: "#ffff00",
              darkItemColor: "#FFFFFF",
              darkItemHoverColor: "#ffff00",

              // // darkSubMenuItemBg: "#003459",
              // itemHoverBg: "#ffff00",

              // itemColor: '#003459',
            },
          },
        }}
      >
        <body className={inter.className}>
          <StyledRegistry>
            <Top />
            <Nav />

            <main>{children}</main>
            <Footer />
          </StyledRegistry>
        </body>
      </ConfigProvider>
    </html>
  );
}
