export const doctorsList = [
  {
    id: 1,
    src: "/beach.jpg",
    alt: "METRO LEMERY MEDICAL CENTER IMAGE",
    name: "Manalo, Celeste Cordova",
    specialty: "PEDIATRICS",
    schedule: "MONDAY TO SATURDAY EXCEPT THURSDAY 10:00AM TO 2:00 PM",
    sec_name: "MARIBETH ZALAMEDA",
    sec_number: "0905-692-1087",
  },
  {
    id: 2,
    src: "/banner.webp",
    alt: "METRO LEMERY MEDICAL CENTER IMAGE",
    name: "Manalo, Francisco Jr. Biscocho",
    specialty: "OPHTHALMOLOGIST - PEDIATRICS",
    schedule: "MONDAY TO SATURDAY EXCEPT THURSDAY 10:00AM TO 2:00 PM",
    sec_name: "ANDREA MARASIGAN",
    sec_number: "0956-327-6161",
  },
  {
    id: 3,
    src: "/farm.jpg",
    alt: "METRO LEMERY MEDICAL CENTER IMAGE",
    name: "Arellano, Mary Grace",
    specialty: "INTERNAL MEDICINE - PULMONOLOGIST",
    schedule: "-",
    sec_name: "NORIECHELLE SALAZAR",
    sec_number: "0975-876-9631",
  },
  {
    id: 4,
    src: "/logo.jpg",
    alt: "METRO LEMERY MEDICAL CENTER IMAGE",
    name: "Jaypee, Avendano",
    specialty: "PEDIATRICS",
    schedule: "MONDAY TO SATURDAY EXCEPT THURSDAY 10:00AM TO 2:00 PM",
    sec_name: "MARIBETH ZALAMEDA",
    sec_number: "0905-692-1087",
  },
  {
    id: 5,
    src: "/hmo/cocolife.png",
    alt: "METRO LEMERY MEDICAL CENTER IMAGE",
    name: "Jose, Penaflor",
    specialty: "OPHTHALMOLOGIST - PEDIATRICS",
    schedule: "MONDAY TO SATURDAY EXCEPT THURSDAY 10:00AM TO 2:00 PM",
    sec_name: "ANDREA MARASIGAN",
    sec_number: "0956-327-6161",
  },
  {
    id: 6,
    src: "/hmo/eastwest.png",
    alt: "METRO LEMERY MEDICAL CENTER IMAGE",
    name: "Jason, Magiba",
    specialty: "INTERNAL MEDICINE - PULMONOLOGIST",
    schedule: "-",
    sec_name: "NORIECHELLE SALAZAR",
    sec_number: "0975-876-9631",
  },
];
